;(function() {
    /** GENERATED BY OCTRiS OUI, DO NOT EDIT! **/
    if (!('rpc' in oui)) {
        oui.rpc = {};
    }
    
{{#foreach($service, $services)}}
    oui.rpc.{{$service:name}} = function({{implode(', ', $service:parameters)}}, _oui_cb) {
        if (typeof _oui_cb == 'undefined') {
            _oui_cb = {};
        }
        
        if (!('success' in _oui_cb)) {
            _oui_cb.success = function(result) {
                console.log(result);
            }
        }
        if (!('error' in _oui_cb)) {
            _oui_cb.error = function() {
            }
        }

        oui.$.ajax({
            'type':     '{{$service:method}}',
            'url':      '{{$service_url}}',
            'data':     {{$service:data}},
            'success':  _oui_cb.success,
            'error':    _oui_cb.error
        });
    }
{{#end}}    
})();
